module.exports = [
    'Ground your attention on yourself. Be conscious at every moment of what you are thinking, sensing, feeling, desiring, and doing.',
    'Always finish what you have begun.',
    'Whatever you are doing, do it as well as possible.',
    'Do not become attached to anything that can destroy you in the course of time.',
    'Develop your generosity ‒ but secretly.',
    'Treat everyone as if he or she was a close relative.',
    'Organize what you have disorganized.',
    'Learn to receive and give thanks for every gift.',
    'Stop defining yourself.',
    'Do not lie or steal, for you lie to yourself and steal from yourself.',
    'Help your neighbor, but do not make him dependent.',
    'Do not encourage others to imitate you.',
    'Make work plans and accomplish them.',
    'Do not take up too much space.',
    'Make no useless movements or sounds.',
    'If you lack faith, pretend to have it.',
    'Do not allow yourself to be impressed by strong personalities.',
    'Do not regard anyone or anything as your possession.',
    'Share fairly.',
    'Do not seduce.',
    'Sleep and eat only as much as necessary.',
    'Do not speak of your personal problems.',
    'Do not express judgment or criticism when you are ignorant of most of the factors involved.',
    'Do not establish useless friendships.',
    'Do not follow fashions.',
    'Do not sell yourself.',
    'Respect contracts you have signed.',
    'Be on time.',
    'Never envy the luck or success of anyone.',
    'Say no more than necessary.',
    'Do not think of the profits your work will engender.',
    'Never threaten anyone.',
    'Keep your promises.',
    'In any discussion, put yourself in the other person’s place.',
    'Admit that someone else may be superior to you.',
    'Do not eliminate, but transmute.',
    'Conquer your fears, for each of them represents a camouflaged desire.',
    'Help others to help themselves.',
    'Conquer your aversions and come closer to those who inspire rejection in you.',
    'Do not react to what others say about you, whether praise or blame.',
    'Transform your pride into dignity.',
    'Transform your anger into creativity.',
    'Transform your greed into respect for beauty.',
    'Transform your envy into admiration for the values of the other.',
    'Transform your hate into charity.',
    'Neither praise nor insult yourself.',
    'Regard what does not belong to you as if it did belong to you.',
    'Do not complain.',
    'Develop your imagination.',
    'Never give orders to gain the satisfaction of being obeyed.',
    'Pay for services performed for you.',
    'Do not proselytize your work or ideas.',
    'Do not try to make others feel for you emotions such as pity, admiration, sympathy, or complicity.',
    'Do not try to distinguish yourself by your appearance.',
    'Never contradict; instead, be silent.',
    'Do not contract debts; acquire and pay immediately.',
    'If you offend someone, ask his or her pardon; if you have offended a person publicly, apologize publicly.',
    'When you realize you have said something that is mistaken, do not persist in error through pride; instead, immediately retract it.',
    'Never defend your old ideas simply because you are the one who expressed them.',
    'Do not keep useless objects.',
    'Do not adorn yourself with exotic ideas.',
    'Do not have your photograph taken with famous people.',
    'Justify yourself to no one, and keep your own counsel.',
    'Never define yourself by what you possess.',
    'Never speak of yourself without considering that you might change.',
    'Accept that nothing belongs to you.',
    'When someone asks your opinion about something or someone, speak only of his or her qualities.',
    'When you become ill, regard your illness as your teacher, not as something to be hated.',
    'Look directly, and do not hide yourself.',
    'Do not forget your dead, but accord them a limited place and do not allow them to invade your life.',
    'Wherever you live, always find a space that you devote to the sacred.',
    'When you perform a service, make your effort inconspicuous.',
    'If you decide to work to help others, do it with pleasure.',
    'If you are hesitating between doing and not doing, take the risk of doing.',
    'Do not try to be everything to your spouse; accept that there are things that you cannot give him or her but which others can.',
    'When someone is speaking to an interested audience, do not contradict that person and steal his or her audience.',
    'Live on money you have earned.',
    'Never brag about amorous adventures.',
    'Never glorify your weaknesses.',
    'Never visit someone only to pass the time.',
    'Obtain things in order to share them.',
    'If you are meditating and a devil appears, make the devil meditate to.',
];